import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/contexts/user-context";
import { getCurrentUserV2 } from "@/lib/auth";

export const metadata: Metadata = {
  title: "PPTU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userPromise = getCurrentUserV2();

  return (
    <html lang="en">
      <body className="min-h-[100dvh] bg-gray-50">
        <UserProvider userPromise={userPromise}>{children}</UserProvider>
      </body>
    </html>
  );
}
